package compiler;
import gen.PhraseForgeLexer;
import gen.PhraseForgeParser;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;

// This is a method named "runPF" that takes a String parameter named "pgmPath".
public class Compiler {
    public void runPF(String pgmPath) {
        try {
            CharStream inpCode = CharStreams.fromFileName(pgmPath);
            PhraseForgeLexer lexer = new PhraseForgeLexer(inpCode);
            CommonTokenStream tokens = new CommonTokenStream(lexer);
            PhraseForgeParser parser = new PhraseForgeParser(tokens);
            // Generating a ParseTree object by parsing the input program file.
            ParseTree pTree = parser.forge_pgm();
            PhraseForgeCompiler compiler = new PhraseForgeCompiler();
            // Visiting the ParseTree object and generating the intermediate code using the compiler object.
            compiler.visit(pTree);
            // Storing the intermediate code generated by the compiler object as a list of strings.
            List<String> iCode= Arrays.asList(compiler.getInterCode().split("\\n"));
            // Printing the number of lines in the intermediate code.
            System.out.println("Compile time: No of lines in intermediate code - " + iCode.size());
            // If the number of lines in the intermediate code is greater than zero, 
            // create a new file with the same name as the input file but with ".pra" extension.
            if (iCode.size() > 0) {
                PrintWriter pw = new PrintWriter(pgmPath.replace("prage", "pra"), StandardCharsets.UTF_8);
                // Writing the intermediate code lines to the new file.
                for (String line : iCode) {
                    pw.println(line);
                }
                pw.close();
            }
        } catch (Exception e) {
            // If any exception occurs during the compilation process, print the stack trace.
            e.printStackTrace();
        }
    }
}